#!/bin/sh

case $1 in
    config)
        cat << 'EOM'
graph_title DSL Noise Margins
graph_args --base 1000 -l 0
graph_vlabel db
graph_category other
graph_info Upstream and Downstream Noise Margins in dB
noise_margin_up_db.label noise-up
noise_margin_up_db.info Noise Margin Upstream (dB)
noise_margin_down_db.label noise-down
noise_margin_down_db.info Noise Margin Downstream (dB)
EOM
        exit 0;;
esac

FILE=/tmp/zyxel-data.txt
if [ ! -f ${FILE} ]; then
    echo "no data in ${FILE}"
    exit 1
fi

echo "noise_margin_up_db.value $(grep 'noise margin upstream' $FILE | awk '{print $4}')"
echo "noise_margin_down_db.value $(grep 'noise margin down' $FILE | awk '{print $4}')"
