#!/bin/sh

case $1 in
    config)
        cat << 'EOM'
graph_title DSL Output Power
graph_args --base 1000 -l 0
graph_vlabel db
graph_category other
graph_info Upstream and Downstream Output Power
output_power_up_db.label power-up
output_power_up_db.info Output Power Upstream (dB)
output_power_down_db.label power-down
output_power_down_db.info Output Power Downstream (dB)
EOM
        exit 0;;
esac

FILE=/tmp/zyxel-data.txt
if [ ! -f ${FILE} ]; then
    echo "no data in ${FILE}"
    exit 1
fi

echo "output_power_up_db.value $(grep 'output power upstream' $FILE | awk '{print $4}')"
echo "output_power_down_db.value $(grep 'output power down' $FILE | awk '{print $4}')"
